version: "3"
services:
  wnc-fe:
    build: .
    image: ntantai21810/wnc
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: ntantai21810/proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wnc-fe
      - certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d www.nguyentai.click -d nguyentai.click --non-interactive --agree-tos -m nguyentantai9a3@gmail.com
