version: "3"
services:
  wnc-fe:
    build: .
    image: ntantai21810/wnc
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: ntantai21810/proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wnc-fe
