version: "3"
services:
  wnc-fe:
    build: .
    volumes:
      - .:/usr/app/src
    image: ntantai21810/wnc
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: ntantai21810/proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - wnc-fe
