# .github/workflows/cicd.yml
name: demo-ci-cd
on:
  push:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push
        uses: docker/bake-action@v2
        with:
          files: ./docker-compose.yaml
          push: true

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf deploy.sh && rm -rf init-nginx.sh && wget https://raw.githubusercontent.com/ntantai21810/wnc-final/master/deploy.sh && wget https://raw.githubusercontent.com/ntantai21810/wnc-final/master/init-nginx.sh && echo ${{ secrets.SU_PASSWORD }} | sudo -S bash init-nginx.sh deploy.sh
